/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eclair_silk_coder_LameCoder */

#ifndef _Included_eclair_silk_coder_LameCoder
#define _Included_eclair_silk_coder_LameCoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eclair_silk_coder_LameCoder
 * Method:    initializeDefault
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eclair_silk_coder_LameCoder_initializeDefault
  (JNIEnv *, jclass);

/*
 * Class:     eclair_silk_coder_LameCoder
 * Method:    initialize
 * Signature: (IIIIFIIIIIIILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_eclair_silk_coder_LameCoder_initialize
  (JNIEnv *, jclass, jint, jint, jint, jint, jfloat, jint, jint, jint, jint, jint, jint, jint, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     eclair_silk_coder_LameCoder
 * Method:    lameClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eclair_silk_coder_LameCoder_lameClose
  (JNIEnv *, jclass);

/*
 * Class:     eclair_silk_coder_LameCoder
 * Method:    encodeFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_eclair_silk_coder_LameCoder_encodeFile
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
