/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eclair_silk_coder_MP3Coder */

#ifndef _Included_eclair_silk_coder_MP3Coder
#define _Included_eclair_silk_coder_MP3Coder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eclair_silk_coder_MP3Coder
 * Method:    decodeMP3
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_eclair_silk_coder_MP3Coder_decodeMP3
  (JNIEnv *, jclass, jstring, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
